---
- name: Ensure apache2 is not installed
  apt:
    name: apache2
    state: absent
    purge: true
    force: true

- name: Ensure nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: Check Nginx status

- name: Sets Nginx conf file
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: Reload Nginx

- name: Get Diffie-Hellman parameter for DHE ciphersuites
  get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/nginx/dhparam.pem
    mode: '0644'
  notify: Reload Nginx

- name: Creates directory for additional conf
  file:
    path: /etc/nginx/nginxconfig.io
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy additional conf files
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/nginxconfig.io/
    owner: root
    group: root
    mode: 0644
  with_items:
    - general.conf
    - php_fastcgi.conf
    - proxy.conf
    - security.conf
  notify: Reload Nginx

